export const SIGNUP = '/signup'
export const SIGNIN = '/signin'
export const FORGETPWD = '/forgetpwd'
export const VERIFICATION = '/verification'
export const SUCCESS = '/success'
export const DASHBOARD = '/dashboard'
export const TASKINSERT = '/dashboard/insert_task'
export const ITEMINSERT = '/dashboard/insert_item'
